# Generated by Django 5.0.3 on 2024-04-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="average_rating",
            field=models.FloatField(null=True),
        ),
    ]
