# Generated by Django 5.0.3 on 2024-04-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
