# Generated by Django 5.0.3 on 2024-04-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_no",
            field=models.CharField(null=True),
        ),
    ]
