# Generated by Django 5.0.3 on 2024-04-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_order_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_no",
            field=models.CharField(),
        ),
    ]
